### PR TITLE
SQLAlchemy 2.0 Support

### PR DESCRIPTION
**Pull request by GabrielGaona**
The extension is not compatible with changes made in SQLAlchemy 2.0 (https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-20-implicit-execution). Updated the query execution to support the new interface that requires execution through the engine's connection. Also wrapped the query in a sqlalchemy text clause object because the new interface requires an executable object.

### CODE REVIEW

**Comment by dhellmann** [comment]
Does this form work with the 1.x series, too, or should we update the minimum requirement for the dependency to be `>= 2.0`?

**Comment by dhellmann** [comment]
> Does this form work with the 1.x series, too, or should we update the minimum requirement for the dependency to be `>= 2.0`?

A quick test shows it is not compatible. I've merged a change to cap the current requirement, so this PR will probably need to update that cap. I also added some CI to verify that it works after that's updated.

If you update this PR, I will modernize the packaging data and produce a new release that includes your change this week.

**Comment by GabrielGaona** [comment]
Thanks for the quick follow up, Doug. I pushed my commit to pin SQLAlchemy>=2.0 to prevent the backwards incompatibility with my changes. Let me know if there's anything else that should be updated in the PR.

**Comment by dhellmann** [comment]
> Thanks for the quick follow up, Doug. I pushed my commit to pin SQLAlchemy>=2.0 to prevent the backwards incompatibility with my changes. Let me know if there's anything else that should be updated in the PR.

Thank you for fixing this! I honestly had no idea it was an issue.

I'll merge this today, but it may be another day or two before I have time to cut the release.

**Comment by GabrielGaona** [comment]
Sounds good! Also, note that this fix should be able to close the following open issue.

https://github.com/sphinx-contrib/sqltable/issues/7

**Pull request merged**
